/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: example.i


extern
#ifdef __cplusplus
  "C"
#endif
  void cgo_panic__example_c006f7311ba4aecc(const char*);
static void _swig_gopanic(const char *p) {
  cgo_panic__example_c006f7311ba4aecc(p);
}



#define SWIG_VERSION 0x040200
#define SWIGGO
#define SWIGMODULE example
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "example.h"


extern int              ivar;
extern short            svar;
extern long             lvar;
extern unsigned int     uivar;
extern unsigned short   usvar;
extern unsigned long    ulvar;
extern signed char      scvar;
extern unsigned char    ucvar;
extern char             cvar;
extern float            fvar;
extern double           dvar;
extern char            *strvar;
extern const char       cstrvar[];
extern int             *iptrvar;
extern char             name[256];

extern Point           *ptptr;
extern Point            pt;


#include <string.h>


extern int  status;
extern char path[256];


extern void  print_vars();
extern int  *new_int(int value);
extern Point *new_Point(int x, int y);
extern char  *Point_print(Point *p);
extern void  pt_print();

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_example_c006f7311ba4aecc(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_example_c006f7311ba4aecc(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_ivar_set_example_c006f7311ba4aecc(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  ivar = arg1;
  
}


intgo _wrap_ivar_get_example_c006f7311ba4aecc() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)ivar;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_svar_set_example_c006f7311ba4aecc(short _swig_go_0) {
  short arg1 ;
  
  arg1 = (short)_swig_go_0; 
  
  svar = arg1;
  
}


short _wrap_svar_get_example_c006f7311ba4aecc() {
  short result;
  short _swig_go_result;
  
  
  result = (short)svar;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_lvar_set_example_c006f7311ba4aecc(long long _swig_go_0) {
  long arg1 ;
  
  arg1 = (long)_swig_go_0; 
  
  lvar = arg1;
  
}


long long _wrap_lvar_get_example_c006f7311ba4aecc() {
  long result;
  long long _swig_go_result;
  
  
  result = (long)lvar;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_uivar_set_example_c006f7311ba4aecc(intgo _swig_go_0) {
  unsigned int arg1 ;
  
  arg1 = (unsigned int)_swig_go_0; 
  
  uivar = arg1;
  
}


intgo _wrap_uivar_get_example_c006f7311ba4aecc() {
  unsigned int result;
  intgo _swig_go_result;
  
  
  result = (unsigned int)uivar;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_usvar_set_example_c006f7311ba4aecc(short _swig_go_0) {
  unsigned short arg1 ;
  
  arg1 = (unsigned short)_swig_go_0; 
  
  usvar = arg1;
  
}


short _wrap_usvar_get_example_c006f7311ba4aecc() {
  unsigned short result;
  short _swig_go_result;
  
  
  result = (unsigned short)usvar;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ulvar_set_example_c006f7311ba4aecc(long long _swig_go_0) {
  unsigned long arg1 ;
  
  arg1 = (unsigned long)_swig_go_0; 
  
  ulvar = arg1;
  
}


long long _wrap_ulvar_get_example_c006f7311ba4aecc() {
  unsigned long result;
  long long _swig_go_result;
  
  
  result = (unsigned long)ulvar;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_scvar_set_example_c006f7311ba4aecc(char _swig_go_0) {
  signed char arg1 ;
  
  arg1 = (signed char)_swig_go_0; 
  
  scvar = arg1;
  
}


char _wrap_scvar_get_example_c006f7311ba4aecc() {
  signed char result;
  char _swig_go_result;
  
  
  result = (signed char)scvar;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ucvar_set_example_c006f7311ba4aecc(char _swig_go_0) {
  unsigned char arg1 ;
  
  arg1 = (unsigned char)_swig_go_0; 
  
  ucvar = arg1;
  
}


char _wrap_ucvar_get_example_c006f7311ba4aecc() {
  unsigned char result;
  char _swig_go_result;
  
  
  result = (unsigned char)ucvar;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_cvar_set_example_c006f7311ba4aecc(char _swig_go_0) {
  char arg1 ;
  
  arg1 = (char)_swig_go_0; 
  
  cvar = arg1;
  
}


char _wrap_cvar_get_example_c006f7311ba4aecc() {
  char result;
  char _swig_go_result;
  
  
  result = (char)cvar;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_fvar_set_example_c006f7311ba4aecc(float _swig_go_0) {
  float arg1 ;
  
  arg1 = (float)_swig_go_0; 
  
  fvar = arg1;
  
}


float _wrap_fvar_get_example_c006f7311ba4aecc() {
  float result;
  float _swig_go_result;
  
  
  result = (float)fvar;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_dvar_set_example_c006f7311ba4aecc(double _swig_go_0) {
  double arg1 ;
  
  arg1 = (double)_swig_go_0; 
  
  dvar = arg1;
  
}


double _wrap_dvar_get_example_c006f7311ba4aecc() {
  double result;
  double _swig_go_result;
  
  
  result = (double)dvar;
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_strvar_set_example_c006f7311ba4aecc(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  {
    delete [] strvar;
    if (arg1) {
      strvar = (char *) (new char[strlen((const char *)arg1)+1]);
      strcpy((char *)strvar, (const char *)arg1);
    } else {
      strvar = 0;
    }
  }
  
  free(arg1); 
}


_gostring_ _wrap_strvar_get_example_c006f7311ba4aecc() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)strvar;
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_cstrvar_get_example_c006f7311ba4aecc() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)(char *)cstrvar;
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_iptrvar_set_example_c006f7311ba4aecc(intgo *_swig_go_0) {
  int *arg1 = (int *) 0 ;
  
  arg1 = *(int **)&_swig_go_0; 
  
  iptrvar = arg1;
  
}


intgo *_wrap_iptrvar_get_example_c006f7311ba4aecc() {
  int *result = 0 ;
  intgo *_swig_go_result;
  
  
  result = (int *)iptrvar;
  *(int **)&_swig_go_result = (int *)result; 
  return _swig_go_result;
}


void _wrap_name_set_example_c006f7311ba4aecc(_gostring_ _swig_go_0) {
  char *arg1 = (char *) (char *)0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  {
    if(arg1) {
      strncpy((char*)name, (const char *)arg1, 256-1);
      name[256-1] = 0;
    } else {
      name[0] = 0;
    }
  }
  
  free(arg1); 
}


_gostring_ _wrap_name_get_example_c006f7311ba4aecc() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)(char *)name;
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_ptptr_set_example_c006f7311ba4aecc(Point *_swig_go_0) {
  Point *arg1 = (Point *) 0 ;
  
  arg1 = *(Point **)&_swig_go_0; 
  
  ptptr = arg1;
  
}


Point *_wrap_ptptr_get_example_c006f7311ba4aecc() {
  Point *result = 0 ;
  Point *_swig_go_result;
  
  
  result = (Point *)ptptr;
  *(Point **)&_swig_go_result = (Point *)result; 
  return _swig_go_result;
}


void _wrap_pt_set_example_c006f7311ba4aecc(Point *_swig_go_0) {
  Point arg1 ;
  Point *argp1 ;
  
  
  argp1 = (Point *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null Point");
  }
  arg1 = (Point)*argp1;
  
  
  pt = arg1;
  
}


Point *_wrap_pt_get_example_c006f7311ba4aecc() {
  Point result;
  Point *_swig_go_result;
  
  
  result = pt;
  *(Point **)&_swig_go_result = new Point(result); 
  return _swig_go_result;
}


intgo _wrap_status_get_example_c006f7311ba4aecc() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)status;
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_path_get_example_c006f7311ba4aecc() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)(char *)path;
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_print_vars_example_c006f7311ba4aecc() {
  print_vars();
  
}


intgo *_wrap_new_int_example_c006f7311ba4aecc(intgo _swig_go_0) {
  int arg1 ;
  int *result = 0 ;
  intgo *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int *)new_int(arg1);
  *(int **)&_swig_go_result = (int *)result; 
  return _swig_go_result;
}


Point *_wrap_new_Point_example_c006f7311ba4aecc(intgo _swig_go_0, intgo _swig_go_1) {
  int arg1 ;
  int arg2 ;
  Point *result = 0 ;
  Point *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (Point *)new_Point(arg1,arg2);
  *(Point **)&_swig_go_result = (Point *)result; 
  return _swig_go_result;
}


_gostring_ _wrap_Point_print_example_c006f7311ba4aecc(Point *_swig_go_0) {
  Point *arg1 = (Point *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(Point **)&_swig_go_0; 
  
  result = (char *)Point_print(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


void _wrap_pt_print_example_c006f7311ba4aecc() {
  pt_print();
  
}


#ifdef __cplusplus
}
#endif

